services:
  server:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: cloud-task-management-api-server
    restart: always
    ports:
      - '${PORT:-3000}:3000'
    develop:
      watch:
        - action: rebuild
          path: ./backend
    env_file:
      - ./backend/.env
    environment:
      - REDIS_HOST=redis 
    depends_on:
      - redis

  redis:
    image: redis:alpine
    container_name: cloud-task-management-api-redis
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

volumes:
  redis_data: